apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
        - name: getting-started
          image: localhost:5000/getting-started
          ports:
            - containerPort: 3000
            
---
apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
spec:
  selector:
    app: getting-started
  ports:
    - protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # port in the pod
      nodePort: 30001
  type: NodePort